# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_tem', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('wind', models.FloatField()),
                ('rain', models.FloatField()),
            ],
        ),
    ]
