# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_scrapping', '0002_weather_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='author',
        ),
    ]
